# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  agda-stdlib = {
    pname = "agda-stdlib";
    version = "0c670dd1794cc55fc2e0887b840cc020e0360da8";
    src = fetchFromGitHub {
      owner = "agda";
      repo = "agda-stdlib";
      rev = "0c670dd1794cc55fc2e0887b840cc020e0360da8";
      fetchSubmodules = false;
      sha256 = "sha256-EF/2FEmtxRyEeKY433bc92zEgQ8gOILMtNdoZIVBJU4=";
    };
    date = "2023-10-19";
  };
}
