# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  agda-stdlib = {
    pname = "agda-stdlib";
    version = "3515c22f3a2c1bd2eeb5fdd504072f67aab3de4d";
    src = fetchFromGitHub {
      owner = "agda";
      repo = "agda-stdlib";
      rev = "3515c22f3a2c1bd2eeb5fdd504072f67aab3de4d";
      fetchSubmodules = false;
      sha256 = "sha256-O0239u7nl9RhAajk+1cIIDAowt//fWfdmsQweigjgGg=";
    };
    date = "2024-01-03";
  };
}
